syntax on
set encoding=utf-8
set expandtab
set tabstop=4
set list
set listchars=tab:▸\ ,trail:▫
set scrolloff=5
set cursorline
set showcmd
set wildmenu
set hlsearch
exec "nohlsearch"

noremap n nzz
noremap N Nzz

map <c-a>k :set nosplitbelow<CR>:split<CR>
map <c-a>j :set splitbelow<CR>:split<CR>
map <c-a>h :set nosplitbelow<CR>:vsplit<CR>
map <c-a>l :set splitbelow<CR>:vsplit<CR>

map <C-k> :res +5<CR>
map <C-j> :res -5<CR>
map <C-h> :vertical resize -5<CR>
map <C-l> :vertical resize +5<CR>

map S :w<CR>
map ZN :set nu<CR>



" === Plug preservim/nerdtree
map tt :NERDTreeToggle<CR>
let NERDTreeMapOpenExpl = ""
let NERDTreeMapUpdir = ""
let NERDTreeMapUpdirKeepOpen = "l"
let NERDTreeMapOpenSplit = ""
let NERDTreeOpenVSplit = ""
let NERDTreeMapActivateNode = "i"
let NERDTreeMapOpenInTab = "o"
let NERDTreeMapPreview = ""
let NERDTreeMapCloseDir = "n"
let NERDTreeMapChangeRoot = "y"





